[project]
name = "mini3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Nikhath Firdose", email = "nikhath.firdose@sjsu.edu" },
    { name = "Veera Vivek Telagani", email = "veeravivek.telagani@sjsu.edu"},
    { name = "Vamshi Raj Nagula", email = "vamshiraj.nagula@sjsu.edu"},
    { name = "Soumith Reddy Podduturi", email = "soumithreddy.podduturi@sjsu.edu" },
]
dependencies = [
    "flask>=3.1.0",
    "requests>=2.32.3",
]

[tool.setuptools]
packages = ["src"]
